# Intro to NumPy

NumPy is a library which provides support for large, homogenous, multi-dimensional arrays and matrices.

In [ ]:
# Importing NumPy library
import numpy as np

## Creating Arrays in NumPy

**Creating a NumPy array from a Python list**

In [60]:
list1 = [10, 20, 30]
list1

[10, 20, 30]

In [59]:
arr1 = np.array(list1)
arr1

array([10, 20, 30])

In [58]:
type(arr1)

numpy.ndarray

**Using arange to create an array**

The difference between .array and .arange is that .array takes a list and turns it into an array. Whereas .arange creates an array from a range of numbers.

In [56]:
arr2 = np.arange(10, 20, 1) # (Start, Stop (inclusive), Step-Size) 
arr2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

## Multidimensional arrays

**Combining two lists --> Two dimensional arrays**

When we combine two arrays together, we add dimensions. So combining two arrays creates a 2d array.

This then allows us to perform matrix operations --> This is why we use NumPy.

In [55]:
# Create a new list to add to the first list
list2 = [40, 50, 60]

# Join the lists together
list3 = [list1, list2]

In [53]:
# Create an array from the joined lists and output, notice the difference?
arr3 = np.array(list3)
arr3

array([[10, 20, 30],
       [40, 50, 60]])

In [54]:
# Let's find the shape of the array
# We have a 2d array, 2 elementsin the first instance (dimension) and 3 in the second (dimension)
arr3.shape

(2, 3)

**Three dimensional arrays**

In [ ]:
arr3dim = np.array([[[1,2,3],[3,4,5]],[[5,6,7],[7,8,9]]])
arr3dim

In [ ]:
arr3dim.shape # 2 sets of list, set lists each set, 3 element per list --> 2, 2, 3

## Using Arrays and Scalars

NumPy arrays allows us to do matrix operations, see below:

In [ ]:
# For example, simple multiplication
arr3dim * 3

In [ ]:
# How is this different to doing:
list3 * 3

Python lists apply the multiplication to the lists themselves, NumPy arrays apply the multiplication to the contents!

**Multiply an array by another array, using a matrix operation:**

In [31]:
# Creating another array which has the same size as arr1
arr11 = np.array(list2)

# Individual numbers will be multiplied based on their positions
# 10 * 40, 20 * 50, 30 * 60 
arr1 * arr11

array([ 400, 1000, 1800])

In [30]:
# What if we tried to multiply arrays of different shapes?
arr1 * arr2

ValueError: operands could not be broadcast together with shapes (3,) (10,) 

In [29]:
# You can however, multiply together arrays of different dimension but the same element size:
arr1 * arr3dim

array([[[ 10,  40,  90],
        [ 30,  80, 150]],

       [[ 50, 120, 210],
        [ 70, 160, 270]]])

## Making arrays task

In [46]:
# 1d array
my_arr_1d = np.arange(1, 13, 1)
my_arr_1d
my_arr_1d.shape

(12,)

In [50]:
# 2d array
my_list_2d = [[1,2,3,4], [5,6,7,8], [9,10,11,12]]
my_arr_2d = np.array(my_list_2d)
my_arr_2d
my_arr_2d.shape

(3, 4)

In [52]:
# 3d array
my_list_3d = [[[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16],[17,18,19,20]],[[100,101,102,103],[104,105,106,107],[108,109,110,110],[111,112,113,114],[115,116,117,118]]]
my_arr_3d = np.array(my_list_3d)
my_arr_3d
my_arr_3d.shape

(2, 5, 4)

## Accessing values in NumPy arrays

In [61]:
# Can we access the 60 value from this array?
arr3

array([[10, 20, 30],
       [40, 50, 60]])

In [62]:
# We can use indexing here
arr3[1][2]

np.int64(60)

In [63]:
# Even faster way to do it
arr3[1, 2]

np.int64(60)

In [64]:
# Access the "bottom" row of the array
arr3[1]

array([40, 50, 60])

In [66]:
# Access each row (:) and then output only the 3rd index (2)
arr3[:,2]

array([30, 60])

## Statistical functions and arrays

There are a number of functions built into NumPy we can use to get things like sum, averages etc.

In [70]:
# Finding the sum of all values in an array
print(arr3.sum())

210


In [71]:
# Finding the sum of values column wise
print(arr3.sum(0))

[50 70 90]


In [73]:
# Finding the sum of values row wise
print(arr3.sum(1))

[ 60 150]


In [75]:
# Finding the mean
print(arr3.mean())

35.0


In [81]:
# Finding standard deviation
print(round(arr3.std(),2))

17.08


In [80]:
# Finding variance
print(arr3.var())

291.6666666666667


In [82]:
# min and max
print(arr3.min())

print(arr3.max())

10
60


## Iterating through NumPy arrays

In [83]:
for x in arr1:
    print(x)

10
20
30


In [86]:
# Looping through n-dimensional arrays --> nest your loops
for dim in arr3:
    for num in dim:
        print(num)

10
20
30
40
50
60


In [88]:
# nditer() stands for n-dimensional iteration. Neater for nested loop when working with arrays.
for x in np.nditer(arr3):
    print(x)

10
20
30
40
50
60


## Saving and loading in NumPy

In [89]:
# Save an array a file
np.save("new", arr3)

In [91]:
# Load the file
loaded_arr = np.load("new.npy")
loaded_arr

array([[10, 20, 30],
       [40, 50, 60]])

In [93]:
# Saving as .txt file
np.savetxt("new.txt", arr3, delimiter=",")

In [94]:
# Loading a .txt file
loaded_from_txt = np.loadtxt("new.txt", delimiter=",")
loaded_from_txt

array([[10., 20., 30.],
       [40., 50., 60.]])